# -*- coding: utf-8 -*-
"""WebScraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lmNk7qoL0WIbtXCeL_sts9Y-NtwgzMRl
"""

#Loading Required Libraries
import requests
from bs4 import BeautifulSoup

URL='https://codegnan.com/'

#Loading the Webpage in Memory using Requests Library
page=requests.get(URL)

#Check the status code of the page
page.status_code

htmlCode=page.text
print(htmlCode)

soup=BeautifulSoup(htmlCode, 'html.parser')
print(soup)

title=soup.title.text
print("Website Title:",title)

headings=soup.find_all("h2")
for heading in headings:
  print(heading.text.strip())

links=soup.find_all("a")
for link in links[:20]:
  print(link.get("href"))

images=soup.find_all("img")
for image in images[:20]:
  print(image.get("src"))

description=soup.find("meta",attrs={"name":"description"})
if description:
  print("Description")
  print(description.get("content"))

scripts=soup.find_all("script")
for script in scripts:
  print(script.get("src"))

og_image=soup.find("meta",property="og:image")
print(og_image["content"])

og_title=soup.find("meta",property="og:title")
print(og_title["content"])

