# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XBEeS85Tb8XDz5JOWxgWZviPK3ySVBE1
"""

import pandas as pd
prices=[2999,1234,6789,3456,5678]
products=["Smartphone","Watch","Earbuds","Laptop","Bluetooth"]
product_prices=pd.Series(prices,index=products)
print(product_prices)

print("Mean:",product_prices.mean())
print("Sum:",product_prices.sum())
print("Min:",product_prices.min())
print("Max:",product_prices.max())

print(product_prices.head(2))
print(product_prices.tail(3))

print(product_prices.apply(lambda x: f'{x+(x*0.18)}'))
print(product_prices.map(lambda x:f"{x}.00"))

print(product_prices.sort_values())
print(product_prices.sort_index())
print(product_prices.sort_index(ascending=False))
print(product_prices.value_counts())

import pandas as pd
data={
"Product":["Smartphone","Laptop","Watch","Earbuds","Bluetooth"],
"Brand":["Apple","Dell","Timex","Soundmax","Echoboom"],
"Price":[2999,4567,1234,7890,6789],
"Stock":[90,80,70,30,20],
"BestSeller":[True,False,True,True,False]
}
df=pd.DataFrame(data)
print(df)

from google.colab import files
import pandas as pd
uploaded=files.upload()
df=pd.read_excel("products_50_rows.xlsx")
print(df)

print(df.shape)
print(df.columns)
print(df.info())

print(df.head(5))
print(df.tail(4))

print(df.iloc[0])
print(df.iloc[1])
print(df["Product"])

print(df)
print(df.loc[2,"Brand"])
print(df.loc[3,"Product"])
print(df.loc[12,"Stock"])
print(df.iloc[4,0])
print(df.iloc[2,1])
print(df.iloc[3,3])

df_dropped=df.drop(columns=["Stock"])
print(df_dropped)

df_renamed=df.rename(columns={"Price":"Cost"})
print(df_renamed)

print(df)
print(df.loc[df["BestSeller"]==True])
print(df.loc[df["Stock"]<40])
print(df.loc[df["Price"]<10000])

df_grouped=df.groupby("Brand").agg({"Price":"mean","Stock":"sum"})
print(df_grouped)
grouped=df.groupby("Brand").agg({"Price":["mean","max","min","sum"]})
print(grouped)
grouped=df.groupby("Brand")["Price"].mean()
print(grouped)

data2={
    "Brand":["Soundmax","TechNova","ByteCore","TimeTrack","EchoBoom"],
    "Rating":[4.2,4.5,4.1,3.8,3.9],
    "Discount":[28,39,16,10,5]
}
df_ratings=pd.DataFrame(data2)
print(df_ratings)

df_merged=df.merge(df_ratings,on="Brand")
print("Merged DataFrame (Adding Ratings):\n",df_merged)

new_data={
    "Product":["Tablet"],
    "Brand":["SmartWare"],
    "Price":[12999],
    "Stock":[25],
    "BestSeller":[True]
}
df_new=pd.DataFrame(new_data)
print(df_new)

df_concat=pd.concat([df,df_new],ignore_index=True)
print("Concatenated DataFrame:\n",df_concat)